import { PrismaClient, Position } from '@prisma/client';

const prisma = new PrismaClient();
/*
const teams = [
  {
    name: 'River Plate',
    country: 'Argentina',
    logoUrl: 'https://cdn.example.com/logos/river-plate.png'
  },
  {
    name: 'Boca Juniors',
    country: 'Argentina',
    logoUrl: 'https://cdn.example.com/logos/boca-juniors.png'
  },
  {
    name: 'Manchester City',
    country: 'England',
    logoUrl: 'https://cdn.example.com/logos/manchester-city.png'
  }
];
*/
const seasons = [
  { year: 2023, name: '2023/24' },
  { year: 2024, name: '2024/25' },
];

type SeedPlayer = {
  name: string;
  birthDate: string;
  nationality: string;
  position: Position;
  photoUrl: string;
  currentTeamName: string;
  stats: Array<{
    seasonYear: number;
    matchesPlayed: number;
    starts: number;
    goals: number;
    assists: number;
    yellowCards: number;
    redCards: number;
    minutesPlayed: number;
    shots: number;
    shotsOnTarget: number;
    keyPasses: number;
    tackles: number;
    interceptions: number;
    dribblesCompleted: number;
    passAccuracy: number;
  }>;
};
/*
const players: ReadonlyArray<SeedPlayer> = [
  {
    name: 'Enzo Fernández',
    birthDate: '2001-01-17T00:00:00.000Z',
    nationality: 'Argentina',
    position: Position.MIDFIELDER,
    photoUrl: 'https://cdn.example.com/players/enzo-fernandez.png',
    currentTeamName: 'Manchester City',
    stats: [
      { seasonYear: 2023, matchesPlayed: 37, starts: 34, goals: 6, assists: 9, yellowCards: 7, redCards: 0, minutesPlayed: 2910, shots: 45, shotsOnTarget: 18, keyPasses: 58, tackles: 89, interceptions: 54, dribblesCompleted: 32, passAccuracy: 88.4 },
      { seasonYear: 2024, matchesPlayed: 41, starts: 39, goals: 7, assists: 11, yellowCards: 6, redCards: 0, minutesPlayed: 3290, shots: 52, shotsOnTarget: 20, keyPasses: 66, tackles: 95, interceptions: 61, dribblesCompleted: 35, passAccuracy: 89.1 }
    ]
  },
  {
    name: 'Lautaro Martínez',
    birthDate: '1997-08-22T00:00:00.000Z',
    nationality: 'Argentina',
    position: Position.FORWARD,
    photoUrl: 'https://cdn.example.com/players/lautaro-martinez.png',
    currentTeamName: 'Boca Juniors',
    stats: [
      { seasonYear: 2023, matchesPlayed: 39, starts: 38, goals: 24, assists: 7, yellowCards: 4, redCards: 0, minutesPlayed: 3125, shots: 116, shotsOnTarget: 53, keyPasses: 34, tackles: 15, interceptions: 8, dribblesCompleted: 49, passAccuracy: 80.3 },
      { seasonYear: 2024, matchesPlayed: 42, starts: 41, goals: 27, assists: 8, yellowCards: 5, redCards: 0, minutesPlayed: 3360, shots: 128, shotsOnTarget: 58, keyPasses: 38, tackles: 18, interceptions: 10, dribblesCompleted: 53, passAccuracy: 81.0 }
    ]
  },
  {
    name: 'Julian Álvarez',
    birthDate: '2000-01-31T00:00:00.000Z',
    nationality: 'Argentina',
    position: Position.FORWARD,
    photoUrl: 'https://cdn.example.com/players/julian-alvarez.png',
    currentTeamName: 'Manchester City',
    stats: [
      { seasonYear: 2023, matchesPlayed: 38, starts: 28, goals: 19, assists: 10, yellowCards: 3, redCards: 0, minutesPlayed: 2510, shots: 92, shotsOnTarget: 41, keyPasses: 43, tackles: 18, interceptions: 12, dribblesCompleted: 41, passAccuracy: 84.1 },
      { seasonYear: 2024, matchesPlayed: 40, starts: 31, goals: 21, assists: 12, yellowCards: 2, redCards: 0, minutesPlayed: 2784, shots: 98, shotsOnTarget: 44, keyPasses: 47, tackles: 21, interceptions: 13, dribblesCompleted: 46, passAccuracy: 84.8 }
    ]
  },
  {
    name: 'Cristian Romero',
    birthDate: '1998-04-27T00:00:00.000Z',
    nationality: 'Argentina',
    position: Position.DEFENDER,
    photoUrl: 'https://cdn.example.com/players/cristian-romero.png',
    currentTeamName: 'Manchester City',
    stats: [
      { seasonYear: 2023, matchesPlayed: 36, starts: 36, goals: 3, assists: 1, yellowCards: 9, redCards: 1, minutesPlayed: 3180, shots: 23, shotsOnTarget: 9, keyPasses: 11, tackles: 96, interceptions: 74, dribblesCompleted: 8, passAccuracy: 87.2 },
      { seasonYear: 2024, matchesPlayed: 39, starts: 39, goals: 4, assists: 2, yellowCards: 8, redCards: 0, minutesPlayed: 3450, shots: 25, shotsOnTarget: 10, keyPasses: 13, tackles: 104, interceptions: 79, dribblesCompleted: 10, passAccuracy: 87.9 }
    ]
  },
  {
    name: 'Kevin De Bruyne',
    birthDate: '1991-06-28T00:00:00.000Z',
    nationality: 'Belgium',
    position: Position.MIDFIELDER,
    photoUrl: 'https://cdn.example.com/players/kevin-de-bruyne.png',
    currentTeamName: 'Manchester City',
    stats: [
      { seasonYear: 2023, matchesPlayed: 31, starts: 28, goals: 9, assists: 17, yellowCards: 2, redCards: 0, minutesPlayed: 2440, shots: 58, shotsOnTarget: 21, keyPasses: 92, tackles: 31, interceptions: 20, dribblesCompleted: 19, passAccuracy: 89.7 },
      { seasonYear: 2024, matchesPlayed: 34, starts: 31, goals: 10, assists: 15, yellowCards: 2, redCards: 0, minutesPlayed: 2620, shots: 61, shotsOnTarget: 24, keyPasses: 88, tackles: 28, interceptions: 18, dribblesCompleted: 17, passAccuracy: 90.1 }
    ]
  }
];
*/

const teams = [
  {
    name: 'Manchester City',
    country: 'England',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/281.png',
  },
  {
    name: 'Real Madrid',
    country: 'Spain',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/418.png',
  },
  {
    name: 'Barcelona',
    country: 'Spain',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/131.png',
  },
  {
    name: 'Bayern Munich',
    country: 'Germany',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/27.png',
  },
  {
    name: 'Paris Saint-Germain',
    country: 'France',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/583.png',
  },
  {
    name: 'Arsenal',
    country: 'England',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/11.png',
  },
  {
    name: 'Liverpool',
    country: 'England',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/31.png',
  },
  {
    name: 'Inter Milan',
    country: 'Italy',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/46.png',
  },
  {
    name: 'AC Milan',
    country: 'Italy',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/5.png',
  },
  {
    name: 'Atletico Madrid',
    country: 'Spain',
    logoUrl: 'https://tmssl.akamaized.net/images/wappen/head/13.png',
  },
];

const players: ReadonlyArray<SeedPlayer> = [
  // GOALKEEPERS
  {
    name: 'Ederson Moraes',
    birthDate: '1993-08-17',
    nationality: 'Brazil',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/238223-1682684144.jpg',
    currentTeamName: 'Manchester City',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 41,
        starts: 41,
        goals: 0,
        assists: 1,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3690,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 5,
        tackles: 2,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 89,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 38,
        starts: 38,
        goals: 0,
        assists: 1,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3420,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 6,
        tackles: 2,
        interceptions: 4,
        dribblesCompleted: 0,
        passAccuracy: 90,
      },
    ],
  },
  {
    name: 'Alisson Becker',
    birthDate: '1992-10-02',
    nationality: 'Brazil',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/105470-1682684144.jpg',
    currentTeamName: 'Liverpool',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 39,
        starts: 39,
        goals: 0,
        assists: 0,
        yellowCards: 1,
        redCards: 0,
        minutesPlayed: 3510,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 4,
        tackles: 1,
        interceptions: 2,
        dribblesCompleted: 0,
        passAccuracy: 85,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 36,
        starts: 36,
        goals: 0,
        assists: 0,
        yellowCards: 1,
        redCards: 0,
        minutesPlayed: 3240,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 5,
        tackles: 1,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 86,
      },
    ],
  },

  // DEFENDERS
  {
    name: 'Ruben Dias',
    birthDate: '1997-05-14',
    nationality: 'Portugal',
    position: Position.DEFENDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/258004-1682684144.jpg',
    currentTeamName: 'Manchester City',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 40,
        starts: 39,
        goals: 2,
        assists: 1,
        yellowCards: 6,
        redCards: 0,
        minutesPlayed: 3500,
        shots: 15,
        shotsOnTarget: 6,
        keyPasses: 10,
        tackles: 60,
        interceptions: 55,
        dribblesCompleted: 5,
        passAccuracy: 92,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 38,
        starts: 38,
        goals: 2,
        assists: 2,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 3400,
        shots: 14,
        shotsOnTarget: 5,
        keyPasses: 12,
        tackles: 62,
        interceptions: 58,
        dribblesCompleted: 6,
        passAccuracy: 93,
      },
    ],
  },

  // MIDFIELDERS
  {
    name: 'Rodri Hernandez',
    birthDate: '1996-06-22',
    nationality: 'Spain',
    position: Position.MIDFIELDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/357565-1682684144.jpg',
    currentTeamName: 'Manchester City',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 52,
        starts: 50,
        goals: 9,
        assists: 10,
        yellowCards: 8,
        redCards: 1,
        minutesPlayed: 4500,
        shots: 60,
        shotsOnTarget: 25,
        keyPasses: 80,
        tackles: 90,
        interceptions: 85,
        dribblesCompleted: 30,
        passAccuracy: 92,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 48,
        starts: 47,
        goals: 8,
        assists: 11,
        yellowCards: 7,
        redCards: 0,
        minutesPlayed: 4300,
        shots: 58,
        shotsOnTarget: 24,
        keyPasses: 85,
        tackles: 95,
        interceptions: 88,
        dribblesCompleted: 32,
        passAccuracy: 93,
      },
    ],
  },

  // FORWARDS
  {
    name: 'Erling Haaland',
    birthDate: '2000-07-21',
    nationality: 'Norway',
    position: Position.FORWARD,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/418560-1682684144.jpg',
    currentTeamName: 'Manchester City',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 45,
        starts: 42,
        goals: 44,
        assists: 6,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3700,
        shots: 160,
        shotsOnTarget: 90,
        keyPasses: 30,
        tackles: 10,
        interceptions: 5,
        dribblesCompleted: 25,
        passAccuracy: 78,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 42,
        starts: 40,
        goals: 40,
        assists: 8,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3500,
        shots: 150,
        shotsOnTarget: 85,
        keyPasses: 35,
        tackles: 12,
        interceptions: 6,
        dribblesCompleted: 28,
        passAccuracy: 79,
      },
    ],
  },
  {
    name: 'Thibaut Courtois',
    birthDate: '1992-05-11',
    nationality: 'Belgium',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/108390-1682684144.jpg',
    currentTeamName: 'Real Madrid',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 30,
        starts: 30,
        goals: 0,
        assists: 0,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 2700,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 2,
        tackles: 1,
        interceptions: 2,
        dribblesCompleted: 0,
        passAccuracy: 84,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 38,
        starts: 38,
        goals: 0,
        assists: 0,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3420,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 3,
        tackles: 1,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 85,
      },
    ],
  },
  {
    name: 'Marc-Andre ter Stegen',
    birthDate: '1992-04-30',
    nationality: 'Germany',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/74857-1682684144.jpg',
    currentTeamName: 'Barcelona',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 42,
        starts: 42,
        goals: 0,
        assists: 1,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3780,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 6,
        tackles: 2,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 88,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 39,
        starts: 39,
        goals: 0,
        assists: 1,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3510,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 7,
        tackles: 2,
        interceptions: 4,
        dribblesCompleted: 0,
        passAccuracy: 89,
      },
    ],
  },
  {
    name: 'Gianluigi Donnarumma',
    birthDate: '1999-02-25',
    nationality: 'Italy',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/315858-1682684144.jpg',
    currentTeamName: 'Paris Saint-Germain',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 40,
        starts: 40,
        goals: 0,
        assists: 0,
        yellowCards: 1,
        redCards: 0,
        minutesPlayed: 3600,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 3,
        tackles: 1,
        interceptions: 2,
        dribblesCompleted: 0,
        passAccuracy: 83,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 41,
        starts: 41,
        goals: 0,
        assists: 0,
        yellowCards: 1,
        redCards: 0,
        minutesPlayed: 3690,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 4,
        tackles: 1,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 84,
      },
    ],
  },

  // DEFENDERS (continuación)
  {
    name: 'Virgil van Dijk',
    birthDate: '1991-07-08',
    nationality: 'Netherlands',
    position: Position.DEFENDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/139208-1682684144.jpg',
    currentTeamName: 'Liverpool',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 42,
        starts: 42,
        goals: 4,
        assists: 2,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 3780,
        shots: 25,
        shotsOnTarget: 10,
        keyPasses: 15,
        tackles: 70,
        interceptions: 65,
        dribblesCompleted: 8,
        passAccuracy: 90,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 40,
        starts: 40,
        goals: 3,
        assists: 2,
        yellowCards: 4,
        redCards: 0,
        minutesPlayed: 3600,
        shots: 22,
        shotsOnTarget: 9,
        keyPasses: 14,
        tackles: 68,
        interceptions: 63,
        dribblesCompleted: 7,
        passAccuracy: 91,
      },
    ],
  },
  {
    name: 'William Saliba',
    birthDate: '2001-03-24',
    nationality: 'France',
    position: Position.DEFENDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/495666-1682684144.jpg',
    currentTeamName: 'Arsenal',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 45,
        starts: 44,
        goals: 2,
        assists: 1,
        yellowCards: 6,
        redCards: 0,
        minutesPlayed: 3900,
        shots: 12,
        shotsOnTarget: 5,
        keyPasses: 10,
        tackles: 75,
        interceptions: 70,
        dribblesCompleted: 10,
        passAccuracy: 91,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 43,
        starts: 43,
        goals: 2,
        assists: 1,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 3800,
        shots: 11,
        shotsOnTarget: 4,
        keyPasses: 11,
        tackles: 78,
        interceptions: 72,
        dribblesCompleted: 11,
        passAccuracy: 92,
      },
    ],
  },

  // MIDFIELDERS (continuación)
  {
    name: 'Jude Bellingham',
    birthDate: '2003-06-29',
    nationality: 'England',
    position: Position.MIDFIELDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/581678-1682684144.jpg',
    currentTeamName: 'Real Madrid',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 42,
        starts: 40,
        goals: 23,
        assists: 12,
        yellowCards: 6,
        redCards: 0,
        minutesPlayed: 3500,
        shots: 110,
        shotsOnTarget: 60,
        keyPasses: 90,
        tackles: 60,
        interceptions: 50,
        dribblesCompleted: 55,
        passAccuracy: 89,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 44,
        starts: 43,
        goals: 20,
        assists: 14,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 3700,
        shots: 105,
        shotsOnTarget: 58,
        keyPasses: 95,
        tackles: 62,
        interceptions: 52,
        dribblesCompleted: 60,
        passAccuracy: 90,
      },
    ],
  },

  // FORWARDS (continuación)
  {
    name: 'Kylian Mbappe',
    birthDate: '1998-12-20',
    nationality: 'France',
    position: Position.FORWARD,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/342229-1682684144.jpg',
    currentTeamName: 'Real Madrid',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 48,
        starts: 46,
        goals: 44,
        assists: 10,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 4100,
        shots: 180,
        shotsOnTarget: 95,
        keyPasses: 70,
        tackles: 15,
        interceptions: 8,
        dribblesCompleted: 90,
        passAccuracy: 82,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 46,
        starts: 45,
        goals: 42,
        assists: 11,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 4000,
        shots: 175,
        shotsOnTarget: 92,
        keyPasses: 75,
        tackles: 16,
        interceptions: 9,
        dribblesCompleted: 95,
        passAccuracy: 83,
      },
    ],
  },
  {
    name: 'Vinicius Junior',
    birthDate: '2000-07-12',
    nationality: 'Brazil',
    position: Position.FORWARD,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/371998-1682684144.jpg',
    currentTeamName: 'Real Madrid',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 45,
        starts: 43,
        goals: 24,
        assists: 18,
        yellowCards: 7,
        redCards: 1,
        minutesPlayed: 3800,
        shots: 140,
        shotsOnTarget: 70,
        keyPasses: 100,
        tackles: 20,
        interceptions: 10,
        dribblesCompleted: 120,
        passAccuracy: 84,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 44,
        starts: 42,
        goals: 26,
        assists: 20,
        yellowCards: 6,
        redCards: 0,
        minutesPlayed: 3700,
        shots: 145,
        shotsOnTarget: 75,
        keyPasses: 105,
        tackles: 22,
        interceptions: 11,
        dribblesCompleted: 125,
        passAccuracy: 85,
      },
    ],
  },
  {
    name: 'Jan Oblak',
    birthDate: '1993-01-07',
    nationality: 'Slovenia',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/121483-1682684144.jpg',
    currentTeamName: 'Atletico Madrid',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 43,
        starts: 43,
        goals: 0,
        assists: 0,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3870,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 2,
        tackles: 1,
        interceptions: 2,
        dribblesCompleted: 0,
        passAccuracy: 80,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 40,
        starts: 40,
        goals: 0,
        assists: 0,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3600,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 3,
        tackles: 1,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 81,
      },
    ],
  },
  {
    name: 'Gregor Kobel',
    birthDate: '1997-12-06',
    nationality: 'Switzerland',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/257814-1682684144.jpg',
    currentTeamName: 'Bayern Munich',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 38,
        starts: 38,
        goals: 0,
        assists: 0,
        yellowCards: 1,
        redCards: 0,
        minutesPlayed: 3420,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 3,
        tackles: 1,
        interceptions: 2,
        dribblesCompleted: 0,
        passAccuracy: 83,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 42,
        starts: 42,
        goals: 0,
        assists: 0,
        yellowCards: 1,
        redCards: 0,
        minutesPlayed: 3780,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 4,
        tackles: 1,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 84,
      },
    ],
  },

  // DEFENDERS (continuación)
  {
    name: 'Josko Gvardiol',
    birthDate: '2002-01-23',
    nationality: 'Croatia',
    position: Position.DEFENDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/475959-1682684144.jpg',
    currentTeamName: 'Manchester City',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 44,
        starts: 42,
        goals: 5,
        assists: 3,
        yellowCards: 6,
        redCards: 0,
        minutesPlayed: 3800,
        shots: 30,
        shotsOnTarget: 12,
        keyPasses: 20,
        tackles: 85,
        interceptions: 70,
        dribblesCompleted: 25,
        passAccuracy: 90,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 45,
        starts: 44,
        goals: 6,
        assists: 4,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 3900,
        shots: 32,
        shotsOnTarget: 14,
        keyPasses: 22,
        tackles: 88,
        interceptions: 72,
        dribblesCompleted: 28,
        passAccuracy: 91,
      },
    ],
  },
  {
    name: 'Achraf Hakimi',
    birthDate: '1998-11-04',
    nationality: 'Morocco',
    position: Position.DEFENDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/398073-1682684144.jpg',
    currentTeamName: 'Paris Saint-Germain',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 46,
        starts: 45,
        goals: 6,
        assists: 8,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 4000,
        shots: 50,
        shotsOnTarget: 20,
        keyPasses: 60,
        tackles: 80,
        interceptions: 65,
        dribblesCompleted: 70,
        passAccuracy: 88,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 44,
        starts: 43,
        goals: 5,
        assists: 9,
        yellowCards: 4,
        redCards: 0,
        minutesPlayed: 3800,
        shots: 48,
        shotsOnTarget: 19,
        keyPasses: 65,
        tackles: 82,
        interceptions: 67,
        dribblesCompleted: 75,
        passAccuracy: 89,
      },
    ],
  },

  // MIDFIELDERS (continuación)
  {
    name: 'Kevin De Bruyne',
    birthDate: '1991-06-28',
    nationality: 'Belgium',
    position: Position.MIDFIELDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/88755-1682684144.jpg',
    currentTeamName: 'Manchester City',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 32,
        starts: 30,
        goals: 10,
        assists: 18,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 2700,
        shots: 90,
        shotsOnTarget: 40,
        keyPasses: 120,
        tackles: 35,
        interceptions: 30,
        dribblesCompleted: 40,
        passAccuracy: 87,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 36,
        starts: 34,
        goals: 9,
        assists: 20,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3000,
        shots: 85,
        shotsOnTarget: 38,
        keyPasses: 125,
        tackles: 38,
        interceptions: 32,
        dribblesCompleted: 42,
        passAccuracy: 88,
      },
    ],
  },
  {
    name: 'Federico Valverde',
    birthDate: '1998-07-22',
    nationality: 'Uruguay',
    position: Position.MIDFIELDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/369081-1682684144.jpg',
    currentTeamName: 'Real Madrid',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 50,
        starts: 48,
        goals: 12,
        assists: 8,
        yellowCards: 7,
        redCards: 0,
        minutesPlayed: 4200,
        shots: 100,
        shotsOnTarget: 45,
        keyPasses: 70,
        tackles: 85,
        interceptions: 75,
        dribblesCompleted: 60,
        passAccuracy: 89,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 48,
        starts: 47,
        goals: 11,
        assists: 9,
        yellowCards: 6,
        redCards: 0,
        minutesPlayed: 4100,
        shots: 95,
        shotsOnTarget: 42,
        keyPasses: 75,
        tackles: 88,
        interceptions: 78,
        dribblesCompleted: 65,
        passAccuracy: 90,
      },
    ],
  },

  // FORWARDS (continuación)
  {
    name: 'Harry Kane',
    birthDate: '1993-07-28',
    nationality: 'England',
    position: Position.FORWARD,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/132098-1682684144.jpg',
    currentTeamName: 'Bayern Munich',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 46,
        starts: 45,
        goals: 44,
        assists: 12,
        yellowCards: 4,
        redCards: 0,
        minutesPlayed: 4000,
        shots: 170,
        shotsOnTarget: 95,
        keyPasses: 60,
        tackles: 12,
        interceptions: 5,
        dribblesCompleted: 30,
        passAccuracy: 81,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 45,
        starts: 44,
        goals: 42,
        assists: 11,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3900,
        shots: 165,
        shotsOnTarget: 92,
        keyPasses: 65,
        tackles: 13,
        interceptions: 6,
        dribblesCompleted: 32,
        passAccuracy: 82,
      },
    ],
  },
  {
    name: 'Bukayo Saka',
    birthDate: '2001-09-05',
    nationality: 'England',
    position: Position.FORWARD,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/433177-1682684144.jpg',
    currentTeamName: 'Arsenal',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 47,
        starts: 46,
        goals: 20,
        assists: 16,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 4100,
        shots: 120,
        shotsOnTarget: 60,
        keyPasses: 110,
        tackles: 40,
        interceptions: 20,
        dribblesCompleted: 85,
        passAccuracy: 85,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 46,
        starts: 45,
        goals: 22,
        assists: 18,
        yellowCards: 4,
        redCards: 0,
        minutesPlayed: 4000,
        shots: 125,
        shotsOnTarget: 65,
        keyPasses: 115,
        tackles: 42,
        interceptions: 22,
        dribblesCompleted: 90,
        passAccuracy: 86,
      },
    ],
  },
  {
    name: 'Mike Maignan',
    birthDate: '1995-07-03',
    nationality: 'France',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/182906-1682684144.jpg',
    currentTeamName: 'AC Milan',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 37,
        starts: 37,
        goals: 0,
        assists: 0,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3330,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 2,
        tackles: 1,
        interceptions: 2,
        dribblesCompleted: 0,
        passAccuracy: 84,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 39,
        starts: 39,
        goals: 0,
        assists: 0,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3510,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 3,
        tackles: 1,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 85,
      },
    ],
  },
  {
    name: 'Andre Onana',
    birthDate: '1996-04-02',
    nationality: 'Cameroon',
    position: Position.GOALKEEPER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/234509-1682684144.jpg',
    currentTeamName: 'Inter Milan',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 41,
        starts: 41,
        goals: 0,
        assists: 1,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3690,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 6,
        tackles: 2,
        interceptions: 3,
        dribblesCompleted: 0,
        passAccuracy: 87,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 40,
        starts: 40,
        goals: 0,
        assists: 1,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3600,
        shots: 0,
        shotsOnTarget: 0,
        keyPasses: 7,
        tackles: 2,
        interceptions: 4,
        dribblesCompleted: 0,
        passAccuracy: 88,
      },
    ],
  },

  // DEFENDERS (final)
  {
    name: 'Trent Alexander-Arnold',
    birthDate: '1998-10-07',
    nationality: 'England',
    position: Position.DEFENDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/314353-1682684144.jpg',
    currentTeamName: 'Liverpool',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 44,
        starts: 42,
        goals: 4,
        assists: 15,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 3700,
        shots: 70,
        shotsOnTarget: 25,
        keyPasses: 120,
        tackles: 65,
        interceptions: 55,
        dribblesCompleted: 50,
        passAccuracy: 87,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 42,
        starts: 41,
        goals: 3,
        assists: 14,
        yellowCards: 4,
        redCards: 0,
        minutesPlayed: 3600,
        shots: 65,
        shotsOnTarget: 23,
        keyPasses: 115,
        tackles: 67,
        interceptions: 57,
        dribblesCompleted: 52,
        passAccuracy: 88,
      },
    ],
  },
  {
    name: 'Alphonso Davies',
    birthDate: '2000-11-02',
    nationality: 'Canada',
    position: Position.DEFENDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/424204-1682684144.jpg',
    currentTeamName: 'Bayern Munich',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 41,
        starts: 40,
        goals: 3,
        assists: 8,
        yellowCards: 4,
        redCards: 0,
        minutesPlayed: 3500,
        shots: 40,
        shotsOnTarget: 15,
        keyPasses: 60,
        tackles: 85,
        interceptions: 70,
        dribblesCompleted: 90,
        passAccuracy: 86,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 43,
        starts: 42,
        goals: 4,
        assists: 9,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3700,
        shots: 45,
        shotsOnTarget: 18,
        keyPasses: 65,
        tackles: 88,
        interceptions: 72,
        dribblesCompleted: 95,
        passAccuracy: 87,
      },
    ],
  },

  // MIDFIELDERS (final)
  {
    name: 'Pedri Gonzalez',
    birthDate: '2002-11-25',
    nationality: 'Spain',
    position: Position.MIDFIELDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/683840-1682684144.jpg',
    currentTeamName: 'Barcelona',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 36,
        starts: 34,
        goals: 6,
        assists: 7,
        yellowCards: 4,
        redCards: 0,
        minutesPlayed: 3000,
        shots: 50,
        shotsOnTarget: 20,
        keyPasses: 85,
        tackles: 55,
        interceptions: 50,
        dribblesCompleted: 70,
        passAccuracy: 91,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 40,
        starts: 38,
        goals: 7,
        assists: 9,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3300,
        shots: 55,
        shotsOnTarget: 22,
        keyPasses: 90,
        tackles: 58,
        interceptions: 52,
        dribblesCompleted: 75,
        passAccuracy: 92,
      },
    ],
  },
  {
    name: 'Jamal Musiala',
    birthDate: '2003-02-26',
    nationality: 'Germany',
    position: Position.MIDFIELDER,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/580195-1682684144.jpg',
    currentTeamName: 'Bayern Munich',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 45,
        starts: 42,
        goals: 15,
        assists: 10,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3600,
        shots: 100,
        shotsOnTarget: 50,
        keyPasses: 95,
        tackles: 50,
        interceptions: 45,
        dribblesCompleted: 110,
        passAccuracy: 88,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 46,
        starts: 44,
        goals: 17,
        assists: 12,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3800,
        shots: 110,
        shotsOnTarget: 55,
        keyPasses: 100,
        tackles: 52,
        interceptions: 47,
        dribblesCompleted: 120,
        passAccuracy: 89,
      },
    ],
  },

  // FORWARDS (final)
  {
    name: 'Mohamed Salah',
    birthDate: '1992-06-15',
    nationality: 'Egypt',
    position: Position.FORWARD,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/148455-1682684144.jpg',
    currentTeamName: 'Liverpool',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 45,
        starts: 44,
        goals: 28,
        assists: 15,
        yellowCards: 3,
        redCards: 0,
        minutesPlayed: 3900,
        shots: 150,
        shotsOnTarget: 80,
        keyPasses: 85,
        tackles: 20,
        interceptions: 10,
        dribblesCompleted: 70,
        passAccuracy: 83,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 44,
        starts: 43,
        goals: 26,
        assists: 14,
        yellowCards: 2,
        redCards: 0,
        minutesPlayed: 3800,
        shots: 145,
        shotsOnTarget: 75,
        keyPasses: 80,
        tackles: 18,
        interceptions: 9,
        dribblesCompleted: 65,
        passAccuracy: 84,
      },
    ],
  },
  {
    name: 'Lautaro Martinez',
    birthDate: '1997-08-22',
    nationality: 'Argentina',
    position: Position.FORWARD,
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/big/406625-1682684144.jpg',
    currentTeamName: 'Inter Milan',
    stats: [
      {
        seasonYear: 2023,
        matchesPlayed: 48,
        starts: 46,
        goals: 30,
        assists: 8,
        yellowCards: 5,
        redCards: 0,
        minutesPlayed: 4100,
        shots: 160,
        shotsOnTarget: 85,
        keyPasses: 40,
        tackles: 15,
        interceptions: 8,
        dribblesCompleted: 50,
        passAccuracy: 79,
      },
      {
        seasonYear: 2024,
        matchesPlayed: 46,
        starts: 45,
        goals: 28,
        assists: 9,
        yellowCards: 4,
        redCards: 0,
        minutesPlayed: 4000,
        shots: 155,
        shotsOnTarget: 82,
        keyPasses: 45,
        tackles: 16,
        interceptions: 9,
        dribblesCompleted: 52,
        passAccuracy: 80,
      },
    ],
  },
];

async function main(): Promise<void> {
  await prisma.playerStats.deleteMany();
  await prisma.player.deleteMany();
  await prisma.season.deleteMany();
  await prisma.team.deleteMany();

  const createdTeams = new Map<string, string>();

  for (const team of teams) {
    const created = await prisma.team.create({ data: team });
    createdTeams.set(created.name, created.id);
  }

  const createdSeasons = new Map<number, string>();

  for (const season of seasons) {
    const created = await prisma.season.create({ data: season });
    createdSeasons.set(created.year, created.id);
  }

  for (const player of players) {
    const teamId = createdTeams.get(player.currentTeamName);
    if (!teamId) {
      throw new Error(`Missing team for player ${player.name}`);
    }

    const createdPlayer = await prisma.player.create({
      data: {
        name: player.name,
        birthDate: new Date(player.birthDate),
        nationality: player.nationality,
        position: player.position,
        photoUrl: player.photoUrl,
        currentTeamId: teamId,
      },
    });

    for (const stat of player.stats) {
      const seasonId = createdSeasons.get(stat.seasonYear);
      if (!seasonId) {
        throw new Error(`Missing season for player ${player.name}`);
      }

      await prisma.playerStats.create({
        data: {
          playerId: createdPlayer.id,
          seasonId,
          matchesPlayed: stat.matchesPlayed,
          starts: stat.starts,
          goals: stat.goals,
          assists: stat.assists,
          yellowCards: stat.yellowCards,
          redCards: stat.redCards,
          minutesPlayed: stat.minutesPlayed,
          shots: stat.shots,
          shotsOnTarget: stat.shotsOnTarget,
          keyPasses: stat.keyPasses,
          tackles: stat.tackles,
          interceptions: stat.interceptions,
          dribblesCompleted: stat.dribblesCompleted,
          passAccuracy: stat.passAccuracy,
        },
      });
    }
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    await prisma.$disconnect();
    console.error(error);
    process.exit(1);
  });
